@BASE_URL = http://localhost:3001/card-holders/
@CARD_ID = 6

GET {{BASE_URL}}

###

POST {{BASE_URL}}
Content-Type: application/json

{
    "fullName": "Mr. {{$randomInt 1 200}}",
    "email": "{{$randomInt 1 200}}@mail.com",
    "department": "Engineering",
    "card": 39
}

###

PUT {{BASE_URL}}/6
Content-Type: application/json

{
    "fullName": "Mr. {{$randomInt 1 200}}",
    "email": "{{$randomInt 1 200}}@mail.com",
    "department": "Engineering",
    "card": 6
}

###

DELETE {{BASE_URL}}/17
Content-Type: application/json

###

POST {{BASE_URL}}check-in
Content-Type: application/json

{
    "rfid": "12345"
}