@BASE_URL = http://localhost:3001/card-holders/
@CARD_ID = 6

GET {{BASE_URL}}

###

POST {{BASE_URL}}
Content-Type: application/json

{
    "full_name": "Mr. {{$randomInt 1 200}}",
    "email": "{{$randomInt 1 200}}@mail.com",
    "department": "Engineering",
    "card": 40
}

###

PUT {{BASE_URL}}/2
Content-Type: application/json

{
    "full_name": "Mr. {{$randomInt 1 200}}",
    "email": "{{$randomInt 1 200}}@mail.com",
    "department": "Engineering",
    "card": 8
}

###

DELETE {{BASE_URL}}/17
Content-Type: application/json

